/** Fallback copy when the backend audit is missing or failed (aligned with Streamlit defaults). */

export const FALLBACK_CONTENT_BIAS_DISCLAIMER =
  'This learning content was generated by an AI system. It may reflect biases present ' +
  'in its training data or source materials. If you notice content that seems biased, ' +
  'culturally insensitive, or inappropriate, please report it so we can improve.';

export const FALLBACK_PROFILE_FAIRNESS_DISCLAIMER =
  'This learner profile was generated by AI based on limited information. ' +
  'Learning style preferences and proficiency levels are estimates and may not ' +
  'fully represent your actual preferences or abilities.';

export const FALLBACK_SKILL_GAP_BIAS_DISCLAIMER =
  'These skill assessments are AI-generated inferences based on the information you provided. ' +
  'They may not fully reflect your actual abilities. Use them as a starting point, not a definitive evaluation.';

/** Collapsible “How your data is used” block on onboarding step 3 (before Begin learning). */
export const ONBOARDING_DATA_USE = {
  title: 'How your data is used',
  sections: [
    {
      heading: 'What we collect',
      body:
        'Your learning goal, and optionally a selected persona and/or resume text. During learning, we also record quiz scores and session timing.',
    },
    {
      heading: 'AI-generated assessments',
      body:
        'Skill levels, learner profiles, and learning content are generated by AI based on the information you provide. They are estimates and may not fully reflect your actual abilities.',
    },
    {
      heading: 'External services',
      body:
        'Your learning goal and background information are sent to an LLM provider (e.g., OpenAI) to generate personalised assessments and content.',
    },
    {
      heading: 'Your control',
      body:
        'You can delete your account and all associated data at any time from the My Profile page. No data is shared with third parties or used for advertising.',
    },
  ],
} as const;
