from .goal_oriented_knowledge_explorer import goal_oriented_knowledge_explorer_system_prompt, goal_oriented_knowledge_explorer_task_prompt
from .search_enhanced_knowledge_drafter import search_enhanced_knowledge_drafter_system_prompt, search_enhanced_knowledge_drafter_task_prompt
from .learning_document_integrator import integrated_document_generator_system_prompt, integrated_document_generator_task_prompt
from .document_quiz_generator import document_quiz_generator_system_prompt, document_quiz_generator_task_prompt
from .learning_content_creator import learning_content_creator_system_prompt, learning_content_creator_task_prompt_outline, learning_content_creator_task_prompt_draft, learning_content_creator_task_prompt_content
