from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class KnowledgeType(str, Enum):
    foundational = "foundational"
    practical = "practical"
    strategic = "strategic"


class KnowledgePoint(BaseModel):
    name: str
    type: KnowledgeType


class KnowledgePoints(BaseModel):
    knowledge_points: List[KnowledgePoint]

class KnowledgeDraft(BaseModel):
    title: str
    content: str
    sources_used: Optional[List[dict]] = None


class DocumentStructure(BaseModel):
    title: str
    overview: str
    summary: str


class SingleChoiceQuestion(BaseModel):
    question: str
    options: List[str]
    correct_option: int | str
    explanation: str | None = None


class MultipleChoiceQuestion(BaseModel):
    question: str
    options: List[str]
    correct_options: List[int | str]
    explanation: str | None = None


class TrueFalseQuestion(BaseModel):
    question: str
    correct_answer: bool
    explanation: str | None = None


class ShortAnswerQuestion(BaseModel):
    question: str
    expected_answer: str
    explanation: str | None = None


class OpenEndedQuestion(BaseModel):
    question: str
    rubric: str  # SOLO-aligned rubric: what constitutes each SOLO level for this question
    example_answer: str  # Model answer at the Relational/Extended Abstract level
    explanation: str | None = None


class DocumentQuiz(BaseModel):
    single_choice_questions: List[SingleChoiceQuestion] = Field(default_factory=list)
    multiple_choice_questions: List[MultipleChoiceQuestion] = Field(default_factory=list)
    true_false_questions: List[TrueFalseQuestion] = Field(default_factory=list)
    short_answer_questions: List[ShortAnswerQuestion] = Field(default_factory=list)
    open_ended_questions: List[OpenEndedQuestion] = Field(default_factory=list)


def parse_knowledge_points(data) -> KnowledgePoints:
    return KnowledgePoints.model_validate(data)


def parse_knowledge_draft(data) -> KnowledgeDraft:
    return KnowledgeDraft.model_validate(data)


def parse_document_structure(data) -> DocumentStructure:
    return DocumentStructure.model_validate(data)


def parse_document_quiz(data) -> DocumentQuiz:
    return DocumentQuiz.model_validate(data)


class MediaResource(BaseModel):
    type: str
    title: str
    url: str
    video_id: str = ""
    thumbnail_url: str = ""
    image_url: str = ""
    description: str = ""


class ContentSection(BaseModel):
    title: str
    summary: str


class ContentOutline(BaseModel):
    title: str
    sections: List[ContentSection] = Field(default_factory=list)


class QuizPair(BaseModel):
    question: str
    answer: str


class LearningContent(BaseModel):
    title: str
    overview: str
    content: str
    summary: str
    quizzes: List[QuizPair] = Field(default_factory=list)


# ── Content Bias Auditor schemas ──────────────────────────────────


class ContentBiasCategory(str, Enum):
    representation_bias = "representation_bias"
    language_bias = "language_bias"
    difficulty_bias = "difficulty_bias"
    source_bias = "source_bias"


class ContentBiasSeverity(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"


class ContentBiasFlag(BaseModel):
    section_title: str
    bias_category: ContentBiasCategory
    severity: ContentBiasSeverity
    explanation: str = Field(..., description="Max 40 words explaining the detected bias.")
    suggestion: str = Field(..., description="Max 30 words suggesting how to fix the bias.")

    @field_validator("explanation")
    @classmethod
    def limit_explanation_words(cls, v: str) -> str:
        if len(v.split()) > 40:
            raise ValueError("Explanation must be 40 words or fewer.")
        return v

    @field_validator("suggestion")
    @classmethod
    def limit_suggestion_words(cls, v: str) -> str:
        if len(v.split()) > 30:
            raise ValueError("Suggestion must be 30 words or fewer.")
        return v


_DEFAULT_CONTENT_ETHICAL_DISCLAIMER = (
    "This learning content was generated by an AI system. It may reflect biases present "
    "in its training data or source materials. If you notice content that seems biased, "
    "culturally insensitive, or inappropriate, please report it so we can improve."
)


class ContentBiasAuditResult(BaseModel):
    bias_flags: List[ContentBiasFlag] = Field(default_factory=list)
    deterministic_flags: List[ContentBiasFlag] = Field(default_factory=list)
    overall_bias_risk: ContentBiasSeverity = ContentBiasSeverity.low
    audited_section_count: int = 0
    flagged_section_count: int = 0
    ethical_disclaimer: str = Field(default=_DEFAULT_CONTENT_ETHICAL_DISCLAIMER)
